# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='poster',
            new_name='posted',
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(related_name='like_ideas', to='great_ideas.User'),
        ),
    ]
