# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('great_ideas', '0003_auto_20180726_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='liked_ideas', to='great_ideas.User')),
                ('posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='great_ideas.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='myjob',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Myjob',
        ),
    ]
