# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('great_ideas', '0004_auto_20180726_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='context',
            new_name='content',
        ),
    ]
