# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_ideas', '0005_auto_20180726_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
