# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_ideas', '0006_auto_20180727_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
