# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('great_ideas', '0008_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(related_name='liked_ideas', to='great_ideas.User'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
